title: naming-convention-liquibase-maven-plugin
description: A lightweight Maven plugin for validating XML Liquibase changeLog files against a customizable set of structural and content rules. This plugin enables teams to enforce Liquibase changeLog standards across codebases with zero runtime dependencies and minimal configuration overhead.
theme: jekyll-theme-slate
